package com.golradreth.nivolet;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.location.Location;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    private static final int PICK=10, PERM=11; private RouteView map; private TextView stats,status; private List<GeoPoint> route=new ArrayList<>(); private Location last; private double walked=0; private boolean tracking=false; private long startMs;
    private final BroadcastReceiver rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){Location l;if(Build.VERSION.SDK_INT>=33)l=i.getParcelableExtra("location",Location.class);else l=i.getParcelableExtra("location");if(l!=null)updateLocation(l);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON); buildUi(); route=GpxStore.load(this);map.setRoute(route); refresh(null);}
    private TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setPadding(20,12,20,12);return t;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
    private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xfff5f1e8);TextView title=tv("Croix du Nivolet • GPS hors-ligne",22);title.setTextColor(0xffffffff);title.setBackgroundColor(0xff173d2a);root.addView(title,new LinearLayout.LayoutParams(-1,-2)); stats=tv("",18);root.addView(stats);status=tv("Aucun GPX importé",15);root.addView(status);map=new RouteView(this);root.addView(map,new LinearLayout.LayoutParams(-1,0,1));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button imp=btn("Importer GPX");Button start=btn("Démarrer / arrêter");Button sos=btn("SOS 112");row.addView(imp,new LinearLayout.LayoutParams(0,-2,1));row.addView(start,new LinearLayout.LayoutParams(0,-2,1));row.addView(sos,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);Button share=btn("Partager ma position");root.addView(share);setContentView(root);imp.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);});start.setOnClickListener(v->toggle());sos.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL, Uri.parse("tel:112"))));share.setOnClickListener(v->sharePos());}
    private void toggle(){if(!tracking){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.POST_NOTIFICATIONS},PERM);return;} tracking=true;walked=0;last=null;startMs=System.currentTimeMillis();startForegroundService(new Intent(this,HikeService.class));status.setText("Suivi GPS actif");}else{tracking=false;stopService(new Intent(this,HikeService.class));status.setText("Suivi arrêté");}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){try{route=GpxStore.importGpx(this,d.getData());map.setRoute(route);status.setText("GPX enregistré hors ligne • "+route.size()+" points");refresh(last);}catch(Exception e){Toast.makeText(this,"Erreur GPX : "+e.getMessage(),Toast.LENGTH_LONG).show();}}}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==PERM&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)toggle();}
    private void updateLocation(Location l){if(last!=null&&l.getAccuracy()<40&&last.distanceTo(l)<250)walked+=last.distanceTo(l);last=l;map.setCurrent(l);refresh(l);}
    private void refresh(Location l){double total=routeLength(route),off=l==null||route.isEmpty()?Double.NaN:distanceToRoute(l,route),finish=l==null||route.isEmpty()?Double.NaN:dist(l,route.get(route.size()-1));String alt=l!=null&&l.hasAltitude()?Math.round(l.getAltitude())+" m":"—";String acc=l!=null?Math.round(l.getAccuracy())+" m":"—";int bat=getSystemService(android.os.BatteryManager.class).getIntProperty(android.os.BatteryManager.BATTERY_PROPERTY_CAPACITY);stats.setText("Trace : "+fmt(total)+"   Marché : "+fmt(walked)+"\nReste à vol d’oiseau : "+fmt(finish)+"   Écart trace : "+fmt(off)+"\nAltitude : "+alt+"   Précision : "+acc+"   Batterie : "+bat+" %");if(!Double.isNaN(off)&&off>80){status.setText("⚠ Tu es à environ "+Math.round(off)+" m du tracé");status.setTextColor(0xffb3261e);if(tracking)((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(android.os.VibrationEffect.createOneShot(450,180));}else status.setTextColor(0xff173d2a);}
    private static double routeLength(List<GeoPoint> r){double d=0;for(int i=1;i<r.size();i++)d+=dist(r.get(i-1),r.get(i));return d;}
    private static double distanceToRoute(Location l,List<GeoPoint> r){double m=Double.MAX_VALUE;for(GeoPoint p:r)m=Math.min(m,dist(l,p));return m;}
    private static double dist(Location l,GeoPoint p){float[] x=new float[1];Location.distanceBetween(l.getLatitude(),l.getLongitude(),p.lat,p.lon,x);return x[0];}
    private static double dist(GeoPoint a,GeoPoint b){float[] x=new float[1];Location.distanceBetween(a.lat,a.lon,b.lat,b.lon,x);return x[0];}
    private static String fmt(double m){if(Double.isNaN(m))return "—";return m>=1000?String.format(Locale.FRANCE,"%.2f km",m/1000):Math.round(m)+" m";}
    private void sharePos(){if(last==null){Toast.makeText(this,"Position GPS indisponible",Toast.LENGTH_SHORT).show();return;}String t="Ma position : https://maps.google.com/?q="+last.getLatitude()+","+last.getLongitude();Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,t);startActivity(Intent.createChooser(i,"Partager la position"));}
    @Override protected void onResume(){super.onResume();registerReceiver(rx,new IntentFilter(HikeService.ACTION),Build.VERSION.SDK_INT>=33?Context.RECEIVER_NOT_EXPORTED:0);}
    @Override protected void onPause(){super.onPause();unregisterReceiver(rx);}
}
